drop table customers;
drop table payments;
drop table products;
drop sequence ID_seq;
drop table existed_files;
create sequence id_seq
START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE TABLE "SCOTT"."CUSTOMERS" 
   (	"ID" NUMBER, 
   	"NAME" VARCHAR2(20 BYTE),
	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(35 BYTE), 
	"DATEOFBIRTH" DATE, 
	"STREETADDRESS" VARCHAR2(40 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE) 

   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
CREATE TABLE "SCOTT"."PAYMENTS" 
   (	"ID" NUMBER(*,0), 
	"PAYMENTID" NUMBER(*,0), 
	"CUSTOMERID" NUMBER(*,0), 
	"PRODUCTID" NUMBER(*,0), 
	"TRANSACTIONDATE" DATE, 
	"CREDITCARD" VARCHAR2(20 BYTE), 
	"CREDITCARDNUMBER" VARCHAR2(20 BYTE),
  "ISINTERSTATE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
CREATE TABLE "SCOTT"."PRODUCTS" 
   (	"PRODUCTS" NUMBER, 
	"PRODUCTNAME" VARCHAR2(100 BYTE), 
	"COMPANYNAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER, 
	"WAREHOUSELOCATIONSTATE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
